[Variables]

skinSize=(#SCREENAREAHEIGHT#*0.5)
lastSetWidth=540

Player=Spotify
alignRight=0

activePlugin=NowPlaying

topTextWidth=208
bottomTextWidth=355

; 0 = MUSIC, 1=GPMDP, 2 = WEBNOWPLAYING
MusicSwitch=0
playerController=Title0
currentlySetName=Spotify (NowPlaying)
currentlySetPlayer=WMP

adaptiveHideActive=1

stowAway=0
stowAwayName=NULL

topText=mArtist
bottomText=mTitle

disableScroll=0

removeExtraFromText=0

thinFont=Metropolis Extra Light
thickFont=Metropolis Medium
controlsFont=Metropolis Medium

mediaTextPositionHor=0
mediaTextAlignment=LeftBottom
mediaTextAlignmentPure=Left
interfaceTextAlignment=Right
nowTextPositionHor=99.9
hairlinePositionHor=116.1
topTextPositionHor=133.65
playCtrlPositionHor=54
settingsTextPositionHor=62.1
indicatorPositionHor=37.8
indicatorPositionHorPure=21.6
conflictIndicatorPositionHor=16.2
conflictIndicatorPositionHorPure=43.2
