[Variables]


;=====================|   NOTE   |=====================


;	Put the icons into the @Resources/Images/Icons/ direcotry (Dock - set icons from Settings skin).
;	To set the icon, input only the name of the file.
;	All icons will be automatically resised to 40x40 format and put a mask on them.
;	Supported image formats: .png, .jpg, .bmp, .gif (no animation), .tif, .ico.


;	To set the app to launch, input the whole path to executable file.
;	The path can be found in app shortcut properties in the "Start in:" or "Location:" fields.
;	Copy the string without the "" signs.


;	To make the indicators work, input the name of the app's process from Task Manager (Processes or Details tab).
;	Leaving this value empty will result in displaying the indicator all the time.
;	To hide the indicators, input random strings (e.g. HIDE).


;	For example of inputing these data, see App1 below.


;=====================|   APPS   |=====================


App1Icon=Aimp.png
App1Path=D:\Program Files (x86)\Opera\launcher.exe
App1Process=opera.exe


App2Icon=Calendar.png
App2Path=
App2Process=HIDE


App3Icon=Flipboard.png
App3Path=
App3Process=HIDE


App4Icon=Live Messenger.png
App4Path=
App4Process=HIDE


App5Icon=Minecraft.png
App5Path=
App5Process=HIDE


App6Icon=Skype.png
App6Path=
App6Process=HIDE


App7Icon=Steam.png
App7Path=
App7Process=HIDE


App8Icon=Zune.png
App8Path=notepad.exe
App8Process=HIDE