[Variables]


;=====================|   NOTE   |=====================


;	Input below your Gmail username and password.
;	Make sure you don't input your whole e-mail address, but only the part before the '@gmail.com' string.
;	Save this file and refresh the Gmail skin.


;	These variables have been hidden to protect your privacy. Hope you don't mind.


;=====================|   GMAIL   |=====================


Username=
Password=