[Variables]


;=====================|   COLORS   |=====================


BackgroundColor=255,255,255


AccentColor=FF4444


FontMainColor=100,100,100
FontShadowColor=50,50,50,100


ObjectMainColor=100,100,100
ObjectShadowColor=200,200,200


;=====================|   HDDS   |====================


Disk1=C
Disk2=D
Disk3=E
Disk4=H


;=====================|   DOCK   |====================


DockGreyscale=0


ColorSwitch=on


;=====================|   PLAYER   |====================


PlayerName=WMP


;=====================|   WEATHER   |====================


Location=Location
Units=m


UnitsSwitch=C


;=====================|   WEATHER   |====================


IP=1
IPMasked=0


MaskSwitch=on
